[package]
name = "shamirust"
version = "0.1.0"
authors = ["Terry Bolt <bolt.terry@gmail.com>"]

[lib]
name = "shamir"

[dependencies]
rust-gmp = { git = "https://github.com/GoldenBadger/rust-gmp.git", branch = "mpz-from-vec-u8" }
rand = "0.3.14"
